languageCode: en-us
baseURL: ""
title: Effective Programmer
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: EffectiveProgrammer
  description: "**Effective Programmer** Ideas for success in software engineering"
  keywords: [Programming, Software Engineering, Career Development]
  author: Effective Programmer
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Effective Programmer"
    icon: "/images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hello! \U0001F44B"
    subtitle: "**Effective Programmer** is a blog about ideas for success in software engineering."
    imageUrl: "images/logo.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Effective Programmer"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: https://github.com/naveed125?tab=repositories

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "**Effective Programmer** Ideas for success in software engineering."

  socialIcons:
    - name: youtube
      url: "http://youtube.com/"
    - name: medium
      url: "https://medium.com/@effective-programmer"
    - name: twitter
      url: "https://twitter.com/naveed_125"
    - name: linkedin
      url: "https://www.linkedin.com/company/effective-programmer"
    - name: github
      url: "https://github.com/naveed125/hugo-docker"
    - name: buymeacoffee
      url: "https://bmc.link/effectiveprgrmr"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/naveed125/hudo-docker"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1
    - identifier: books
      name: Books
      url: /books/
      weight: 2
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
